[colors]
background = '#f8f9fa'
foreground = '#5c6166'
ansi = [
  '#f8f9fa',
  '#f07171',
  '#86b300',
  '#ffaa33',
  '#55b4d4',
  '#a37acc',
  '#4cbf99',
  '#5c6166',
]
brights = [
  '#8a9199',
  '#e65050',
  '#86b300',
  '#ffaa33',
  '#55b4d4',
  '#a37acc',
  '#4cbf99',
  '#abadb1',
]

[metadata]
author = 'PinguinFrosch'
name = 'ayu-light'
