[colors]
background = '#0b0e14'
foreground = '#bfbdb6'
ansi = [
  '#0b0e14',
  '#f07178',
  '#aad94c',
  '#e6b450',
  '#39bae6',
  '#d2a6ff',
  '#95e6cb',
  '#bfbdb6',
]
brights = [
  '#565b66',
  '#d95757',
  '#aad94c',
  '#e6b450',
  '#39bae6',
  '#d2a6ff',
  '#95e6cb',
  '#636a72',
]

[metadata]
author = 'PinguinFrosch'
name = 'ayu-dark'
