[colors]
background = '#282c34'
foreground = '#abb2bf'
ansi = [
  '#181a1f',
  '#e86671',
  '#98c379',
  '#e5c07b',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#abb2bf',
]
brights = [
  '#5c6370',
  '#e86671',
  '#98c379',
  '#e5c07b',
  '#61afef',
  '#c678dd',
  '#56b6c2',
  '#abb2bf',
]

[metadata]
author = 'PinguinFrosch'
name = 'onedark-dark'
