[colors]
background = '#fafafa'
foreground = '#383a42'
ansi = [
  '#101012',
  '#e45649',
  '#50a14f',
  '#986801',
  '#4078f2',
  '#a626a4',
  '#0184bc',
  '#383a42',
]
brights = [
  '#a0a1a7',
  '#e45649',
  '#50a14f',
  '#986801',
  '#4078f2',
  '#a626a4',
  '#0184bc',
  '#383a42',
]

[metadata]
author = 'PinguinFrosch'
name = 'onedark-light'
