[colors]
background = '#161616'
foreground = '#d0d0d0'
ansi = [
  '#262626',
  '#33b1ff',
  '#be95ff',
  '#42be65',
  '#78a9ff',
  '#82cfff',
  '#3ddbd9',
  '#f2f2f2',
]
brights = [
  '#525252',
  '#33b1ff',
  '#be95ff',
  '#42be65',
  '#78a9ff',
  '#82cfff',
  '#08bdba',
  '#ffffff',
]

[metadata]
author = 'PinguinFrosch'
name = 'oxocarbon-dark'
