[colors]
background = '#e1e2e7'
foreground = '#3760bf'
ansi = [
  '#b4b5b9',
  '#f52a65',
  '#587539',
  '#8c6c3e',
  '#2e7de9',
  '#9854f1',
  '#007197',
  '#6172b0',
]
brights = [
  '#a1a6c5',
  '#ff4774',
  '#5c8524',
  '#a27629',
  '#358aff',
  '#a463ff',
  '#007ea8',
  '#3760bf',
]

[metadata]
author = 'PinguinFrosch'
name = 'tokyonight-light'
